# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_added_entries": "00_core.ipynb",
         "get_removed_entries": "00_core.ipynb",
         "get_modified_entries": "00_core.ipynb",
         "logging": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://tkanngiesser.github.io/deltaframe/"

git_url = "https://github.com/tkanngiesser/deltaframe/tree/master/"

def custom_doc_links(name): return None
