# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_added": "00_delta.ipynb",
         "get_removed": "00_delta.ipynb",
         "get_modified": "00_delta.ipynb",
         "get_delta": "00_delta.ipynb",
         "log_delta": "00_delta.ipynb"}

modules = ["core.py"]

doc_url = "https://tkanngiesser.github.io/deltaframe/"

git_url = "https://github.com/tkanngiesser/deltaframe/tree/master/"

def custom_doc_links(name): return None
